const PersonsData = [
  {
    id: 0,
    name: "Abbos",
    fullName: "Erkinov Sherzod o'g'li",
    age: 20,
    company: "TSUE",
    email: "erkinov0247@gmail.com",
    phone: "+99890#######",
    website: "stadion.uz",
    hovering: false,
  },
  {
    id: 1,
    name: "Temur",
    fullName: "Suvonov Husanovich",
    company: "Nordik University",
    age: 22,
    email: "suvonov2008@gmail.com",
    phone: "+9989########",
    website: "stadion.uz",
    hovering: false,
  },
  {
    id: 2,
    name: "Behzod",
    fullName: "Jumayev Farhod o'g'li",
    age: 19,
    company: "Registan LC",
    email: "jumayev2010@gmail.com",
    phone: "+998########",
    website: "stadion.uz",
    hovering: false,
  },
  {
    id: 3,
    name: "Behzod",
    fullName: "Jumayev Farhod o'g'li",
    age: 19,
    company: "Registan LC",
    email: "jumayev2010@gmail.com",
    phone: "+99890#######",
    website: "stadion.uz",
    hovering: false,
  },
];
export default PersonsData;
